### ISSUE TITLE
Please avoid pushing sensitive information like API keys and tokens

### ISSUE THREAD

**Issue by nyashaChiza** [charmainemimie/openAI-content-generator#1]
Hi Charmaine

I noticed that some sensitive information, such as the API key  for openai, has been committed to the repository. Exposing such data in a public repository can lead to security vulnerabilities, including unauthorized access to services or accounts.

To improve the security of your project, I suggest the following:

1. **Remove the sensitive information** from the repository history.
   You can follow [this guide](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) to completely remove sensitive information from Git history.

2. **Use environment variables** to store keys, tokens, and other sensitive information. You can add these variables to a `.env` file and load them into your application using a library like [python-dotenv](https://pypi.org/project/python-dotenv/) for Python, or the equivalent for your programming language.

3. **Add the `.env` file to your `.gitignore`** to ensure it isn't pushed to the repository:
   ```bash
   echo '.env' >> .gitignore
   ```

4. **Consider using a secrets manager** for more secure management of credentials, such as AWS Secrets Manager or Google Cloud Secrets Manager.

Let me know if you need any help implementing these suggestions!

Best regards,

**Comment by charmainemimie** [comment]
Hi Nyasha,

Thank you so much for the feedback. I will work on improving the security
of this project.

Kind regards,

Charmaine
